version: '3.8'

services:
  netshield-dns:
    build: .
    container_name: netshield-v2
    restart: always
    network_mode: "host"
    tmpfs:
      - /var/log
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - ./data:/data
