version: '3.8'

services:
  netshield-dns:
    build: .
    container_name: netshield-v2
    restart: always
    # Host Network Mode: Eliminasi Docker NAT proxy overhead.
    # Paket UDP langsung menyentuh kernel tanpa perantara.
    # Wajib untuk mencapai 126k+ QPS!
    network_mode: host
    tmpfs:
      - /var/log/netshield
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    sysctls:
      # Perbesar buffer penerimaan/pengiriman UDP (16MB)
      net.core.rmem_max: 16777216
      net.core.rmem_default: 8388608
      net.core.wmem_max: 16777216
      net.core.wmem_default: 8388608
      # Perbesar antrian backlog jaringan
      net.core.netdev_max_backlog: 65536
      net.core.somaxconn: 65536
    volumes:
      - ./data:/data
