version: '3.8'

services:
  netshield-dns:
    build: .
    container_name: netshield-v2
    restart: always
    # Host Networking: eliminasi Docker NAT overhead
    # Sysctl tuning dilakukan oleh deploy.sh di level OS
    network_mode: host
    tmpfs:
      - /var/log/netshield
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - ./data:/data
