[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:pdns]
command=/usr/sbin/pdns_recursor --daemon=no --config-dir=/etc/powerdns
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisor/pdns-err.log
stderr_logfile_maxbytes=50MB

[program:unbound]
command=/usr/sbin/unbound -d -c /etc/powerdns/unbound.conf
autostart=true
autorestart=true
priority=8
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:go-api]
command=/usr/local/bin/netshield-api
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
[program:dnsdist]
command=/usr/bin/dnsdist --supervised --config=/etc/powerdns/dnsdist.conf
autostart=true
autorestart=true
priority=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisor/dnsdist-err.log
stderr_logfile_maxbytes=50MB

[program:gobgp]
command=/usr/local/bin/gobgpd -f /etc/gobgpd.toml
autostart=true
autorestart=true
priority=15
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
