package main

import (
	"log"
	"os"
	"os/exec"
	"strings"
	"fmt"
)

// GenerateConfigs reads all settings from SQLite and generates recursor.conf and dnsdist.conf
func GenerateConfigs() error {
	log.Println("[Engine] Generating System Configurations...")

	// 1. Fetch settings from DB
	settings := make(map[string]string)
	rows, err := db.Query("SELECT key, value FROM settings")
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var k, v string
			rows.Scan(&k, &v)
			settings[k] = v
		}
	} else {
		return err
	}

	// Extract specific settings or use defaults
	dohEnabled := settings["doh_enabled"] == "true"
	dotEnabled := settings["dot_enabled"] == "true"
	dnssec := settings["dnssec_enabled"] == "true"
	
	// parent_resolvers typically comma separated IPs
	forwarders := settings["parent_resolvers"]
	if forwarders == "" {
		forwarders = "8.8.8.8, 1.1.1.1" // Default
	}

	// 1.5 Generate Zone Files
	authZonesStr, err := GenerateZoneFiles()
	if err != nil {
		log.Println("[Engine] Failed to generate zone files:", err)
	}

	// 2. Generate recursor.conf
	err = generateRecursorConf(dnssec, forwarders, authZonesStr)
	if err != nil {
		return err
	}

	// 3. Generate dnsdist.conf
	err = generateDnsdistConf(dohEnabled, dotEnabled)
	if err != nil {
		return err
	}

	log.Println("[Engine] Configurations created. Reloading Supervior services...")
	
	// Restart DNS services to apply configs
	exec.Command("supervisorctl", "restart", "pdns").Run()
	exec.Command("supervisorctl", "restart", "dnsdist").Run()

	return nil
}

func generateRecursorConf(dnssec bool, forwarders string, authZones string) error {
	dnssecStr := "off"
	if dnssec {
		dnssecStr = "validate"
	}

	// Clean up forwarders list to ensure spaces
	forwardersClean := strings.ReplaceAll(forwarders, ",", ", ")

	authZoneLine := ""
	if authZones != "" {
		authZoneLine = "auth-zones=" + authZones
	}

	content := fmt.Sprintf(`
# AUTO-GENERATED BY NETSHIELD V6 ENGINE - DO NOT EDIT MANUALLY
# ALL CHANGES WILL BE OVERWRITTEN

# Networking
local-address=127.0.0.1
local-port=5354
threads=4
socket-dir=/var/run/pdns-recursor/

# Security & DNSSEC
dnssec=%s

# Forwarding
forward-zones-recurse=.=%s

# Local Zones (Technitium-style authoritative overrides)
%s

# Tuning for carrier-grade
max-cache-entries=1000000
new-domain-tracking=yes
query-cache-flush-interval=300

# Include Zone and RPZ overrides
lua-config-file=/etc/powerdns/recursor.lua
`, dnssecStr, forwardersClean, authZoneLine)

	return os.WriteFile("/etc/powerdns/recursor.conf", []byte(content), 0644)
}

func generateDnsdistConf(doh bool, dot bool) error {
	content := `
-- AUTO-GENERATED BY NETSHIELD V6 ENGINE - DO NOT EDIT MANUALLY
-- ALL CHANGES WILL BE OVERWRITTEN

-- Core Listeners
addLocal("0.0.0.0:53")
addLocal("[::]:53")

`
	if dot {
		content += `-- DoT Listener (Needs valid certs)
addTLSLocal("0.0.0.0:853", "/etc/ssl/certs/cert.pem", "/etc/ssl/private/key.pem")
`
	}

	if doh {
		content += `-- DoH Listener (Needs valid certs)
addDOHLocal("0.0.0.0:443", "/etc/ssl/certs/cert.pem", "/etc/ssl/private/key.pem", "/dns-query")
`
	}

	content += `
-- Upstream powerdns recursor
newServer({address="127.0.0.1:5354", pool="auth_and_recursor"})

-- Performance tuning
setRingBuffersSize(10000000, 100)
setMaxUDPOutstanding(65535)

-- Web Console
webserver("0.0.0.0:8083", "admin", "admin")
`

	return os.WriteFile("/etc/powerdns/dnsdist.conf", []byte(content), 0644)
}
