package main

import (
	"log"
	"os"
	"os/exec"
	"strings"
	"fmt"
)

// GenerateConfigs reads all settings from SQLite and generates recursor.conf and dnsdist.conf
func GenerateConfigs() error {
	log.Println("[Engine] Generating System Configurations...")

	// 1. Fetch settings from DB
	settings := make(map[string]string)
	rows, err := db.Query("SELECT key, value FROM settings")
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var k, v string
			rows.Scan(&k, &v)
			settings[k] = v
		}
	} else {
		return err
	}

	// Extract specific settings or use defaults
	dohEnabled := settings["doh_enabled"] == "true"
	dotEnabled := settings["dot_enabled"] == "true"
	dnssec := settings["dnssec_enabled"] == "true"
	resolverMode := settings["resolver_mode"]
	if resolverMode == "" {
		resolverMode = "hybrid"
	}
	
	// parent_resolvers typically comma separated IPs
	forwarders := settings["parent_resolvers"]
	if forwarders == "" {
		forwarders = "8.8.8.8, 1.1.1.1" // Default
	}

	// 1.5 Generate Zone Files
	authZonesStr, err := GenerateZoneFiles()
	if err != nil {
		log.Println("[Engine] Failed to generate zone files:", err)
	}

	// 2. Generate recursor.conf
	err = generateRecursorConf(dnssec, forwarders, authZonesStr, resolverMode)
	if err != nil {
		return err
	}

	// 3. Generate dnsdist.conf
	err = generateDnsdistConf(dohEnabled, dotEnabled, forwarders, resolverMode)
	if err != nil {
		return err
	}

	log.Println("[Engine] Configurations created. Reloading Supervior services...")
	
	// Restart DNS services to apply configs
	exec.Command("supervisorctl", "restart", "pdns").Run()
	exec.Command("supervisorctl", "restart", "dnsdist").Run()

	return nil
}

func generateRecursorConf(dnssec bool, forwarders string, authZones string, resolverMode string) error {
	dnssecStr := "off"
	if dnssec {
		dnssecStr = "validate"
	}

	// Evaluate forward-zones-recurse
	forwardZoneConfig := ""
	if resolverMode == "forward_only" {
		// Clean up forwarders list to ensure spaces
		forwardersClean := strings.ReplaceAll(forwarders, ",", ", ")
		
		finalForwarders := []string{}
		for _, f := range strings.Split(forwardersClean, ",") {
			fw := strings.TrimSpace(f)
			if fw != "" && !strings.Contains(fw, ":853") {
				finalForwarders = append(finalForwarders, fw)
			}
		}
		
		if len(finalForwarders) > 0 {
			forwardZoneConfig = fmt.Sprintf("forward-zones-recurse=.=%s", strings.Join(finalForwarders, ", "))
		}
	}

	authZoneLine := ""
	if authZones != "" {
		authZoneLine = "auth-zones=" + authZones
	}

	content := fmt.Sprintf(`
# AUTO-GENERATED BY NETSHIELD V6 ENGINE - DO NOT EDIT MANUALLY
# ALL CHANGES WILL BE OVERWRITTEN

# Networking
local-address=127.0.0.1
local-port=5354
threads=4
socket-dir=/var/run/pdns-recursor/

# Security & DNSSEC
dnssec=%s

# Forwarding
%s

# Local Zones (Technitium-style authoritative overrides)
%s

# Tuning for carrier-grade
max-cache-entries=1000000
new-domain-tracking=yes
query-cache-flush-interval=300

# Include Zone and RPZ overrides
lua-config-file=/etc/powerdns/recursor.lua
`, dnssecStr, forwardZoneConfig, authZoneLine)

	return os.WriteFile("/etc/powerdns/recursor.conf", []byte(content), 0644)
}

func generateDnsdistConf(doh bool, dot bool, forwarders string, resolverMode string) error {
	content := `
-- AUTO-GENERATED BY NETSHIELD V6 ENGINE - DO NOT EDIT MANUALLY
-- ALL CHANGES WILL BE OVERWRITTEN

-- Core Listeners
addLocal("0.0.0.0:53")
addLocal("[::]:53")

`
	if dot {
		content += `-- DoT Listener (Needs valid certs)
addTLSLocal("0.0.0.0:853", "/etc/ssl/certs/cert.pem", "/etc/ssl/private/key.pem")
`
	}

	if doh {
		content += `-- DoH Listener (Needs valid certs)
addDOHLocal("0.0.0.0:443", "/etc/ssl/certs/cert.pem", "/etc/ssl/private/key.pem", "/dns-query")
`
	}

	content += `
-- Define Server Policy
setServerPolicy(firstAvailable) -- Prioritize order=1 (Local Root), then order=2 (Forwarders)

-- Upstream powerdns recursor (Root Natively)
newServer({address="127.0.0.1:5354", pool="main_pool", order=1})
`

	if resolverMode == "forward_only" || resolverMode == "hybrid" {
		for _, f := range strings.Split(forwarders, ",") {
			fw := strings.TrimSpace(f)
			if fw != "" {
				poolName := "main_pool"
				order := "2" // Hybrid uses forwarders as fallback/second-choice
				
				if resolverMode == "forward_only" {
					order = "1" // Forward Only makes them primary
					// We can technically just place it in dot_upstream, but we unified it to main_pool
				}
				
				if strings.Contains(fw, ":853") {
					content += fmt.Sprintf("newServer({address=\"%s\", tls=\"openssl\", pool=\"%s\", order=%s})\n", fw, poolName, order)
				} else if resolverMode == "hybrid" {
					// Add plain forwarders to dnsdist in hybrid mode
					content += fmt.Sprintf("newServer({address=\"%s\", pool=\"%s\", order=%s})\n", fw, poolName, order)
				}
			}
		}
	}
	
	if resolverMode == "forward_only" {
		// If forward strictly, disable root server from pool
		content += "\naddAction(AllRule(), PoolAction(\"main_pool\"))\n"
	} else if resolverMode == "hybrid" {
		// Hybrid uses main_pool (Root is order=1, Forwarders are order=2)
		content += "\naddAction(AllRule(), PoolAction(\"main_pool\"))\n"
	} else {
		// Root Only
		content += "\naddAction(AllRule(), PoolAction(\"main_pool\"))\n"
	}

	content += `
-- Performance tuning
setRingBuffersSize(10000000, 100)
setMaxUDPOutstanding(65535)

-- Web Console
webserver("0.0.0.0:8083", "admin", "admin")
`

	return os.WriteFile("/etc/powerdns/dnsdist.conf", []byte(content), 0644)
}
