package main

import (
	"log"
	"os"
	"os/exec"
	"strings"
	"fmt"
)

// GenerateConfigs reads all settings from SQLite and generates recursor.conf and dnsdist.conf
func GenerateConfigs() error {
	log.Println("[Engine] Generating System Configurations...")

	// 1. Fetch settings from DB
	settings := make(map[string]string)
	rows, err := db.Query("SELECT key, value FROM settings")
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var k, v string
			rows.Scan(&k, &v)
			settings[k] = v
		}
	} else {
		return err
	}

	// Extract specific settings or use defaults
	dohEnabled := settings["doh_enabled"] == "true"
	dotEnabled := settings["dot_enabled"] == "true"
	dnssec := settings["dnssec_enabled"] == "true"
	resolverMode := settings["resolver_mode"]
	if resolverMode == "" {
		resolverMode = "hybrid"
	}
	
	// parent_resolvers typically comma separated IPs
	forwarders := settings["parent_resolvers"]
	if forwarders == "" {
		forwarders = "8.8.8.8, 1.1.1.1" // Default
	}

	// 1.5 Generate Zone Files
	authZonesStr, err := GenerateZoneFiles()
	if err != nil {
		log.Println("[Engine] Failed to generate zone files:", err)
	}

	// 2. Generate recursor.conf
	err = generateRecursorConf(dnssec, forwarders, authZonesStr, resolverMode)
	if err != nil {
		return err
	}

	// 3. Generate dnsdist.conf
	err = generateDnsdistConf(dohEnabled, dotEnabled, forwarders, resolverMode)
	if err != nil {
		return err
	}

	log.Println("[Engine] Configurations created. Reloading Supervior services...")
	
	// Restart DNS services to apply configs
	exec.Command("supervisorctl", "restart", "pdns").Run()
	exec.Command("supervisorctl", "restart", "dnsdist").Run()

	return nil
}

func generateRecursorConf(dnssec bool, forwarders string, authZones string, resolverMode string) error {
	dnssecStr := "off"
	if dnssec {
		dnssecStr = "validate"
	}

	// Evaluate forward-zones-recurse
	forwardZoneConfig := ""
	if resolverMode != "root_only" {
		// Clean up forwarders list to ensure spaces
		forwardersClean := strings.ReplaceAll(forwarders, ",", ", ")
		
		// If ANY forwarder contains :853, we strip it out from recursor.conf because dnsdist handles DoT
		finalForwarders := []string{}
		for _, f := range strings.Split(forwardersClean, ",") {
			fw := strings.TrimSpace(f)
			if fw != "" && !strings.Contains(fw, ":853") {
				finalForwarders = append(finalForwarders, fw)
			}
		}
		
		if len(finalForwarders) > 0 {
			forwardZoneConfig = fmt.Sprintf("forward-zones-recurse=.=%s", strings.Join(finalForwarders, ", "))
		}
		// If all forwarders were :853, forwardZoneConfig remains empty, recursor goes to roots as fallback, but dnsdist catches it first!
	}

	authZoneLine := ""
	if authZones != "" {
		authZoneLine = "auth-zones=" + authZones
	}

	content := fmt.Sprintf(`
# AUTO-GENERATED BY NETSHIELD V6 ENGINE - DO NOT EDIT MANUALLY
# ALL CHANGES WILL BE OVERWRITTEN

# Networking
local-address=127.0.0.1
local-port=5354
threads=4
socket-dir=/var/run/pdns-recursor/

# Security & DNSSEC
dnssec=%s

# Forwarding
%s

# Local Zones (Technitium-style authoritative overrides)
%s

# Tuning for carrier-grade
max-cache-entries=1000000
new-domain-tracking=yes
query-cache-flush-interval=300

# Include Zone and RPZ overrides
lua-config-file=/etc/powerdns/recursor.lua
`, dnssecStr, forwardZoneConfig, authZoneLine)

	return os.WriteFile("/etc/powerdns/recursor.conf", []byte(content), 0644)
}

func generateDnsdistConf(doh bool, dot bool, forwarders string, resolverMode string) error {
	content := `
-- AUTO-GENERATED BY NETSHIELD V6 ENGINE - DO NOT EDIT MANUALLY
-- ALL CHANGES WILL BE OVERWRITTEN

-- Core Listeners
addLocal("0.0.0.0:53")
addLocal("[::]:53")

`
	if dot {
		content += `-- DoT Listener (Needs valid certs)
addTLSLocal("0.0.0.0:853", "/etc/ssl/certs/cert.pem", "/etc/ssl/private/key.pem")
`
	}

	if doh {
		content += `-- DoH Listener (Needs valid certs)
addDOHLocal("0.0.0.0:443", "/etc/ssl/certs/cert.pem", "/etc/ssl/private/key.pem", "/dns-query")
`
	}

	content += `
-- Upstream powerdns recursor
newServer({address="127.0.0.1:5354", pool="auth_and_recursor"})
`

	// Catch DoT upstreams (e.g., 1.1.1.1:853)
	if resolverMode != "root_only" {
		dotServers := []string{}
		for _, f := range strings.Split(forwarders, ",") {
			fw := strings.TrimSpace(f)
			if strings.Contains(fw, ":853") {
				dotServers = append(dotServers, fw)
			}
		}

		if len(dotServers) > 0 {
			content += "\n-- Outgoing Upstream DNS-over-TLS (DoT)\n"
			for _, ds := range dotServers {
				content += fmt.Sprintf("newServer({address=\"%s\", tls=\"openssl\", pool=\"dot_upstream\"})\n", ds)
			}
			
			// If Hybrid mode, we still favor DoT but drop to recursor if DoT fails or if specific rule applies.
			// But Dnsdist routing is typically sequential. 
			// We can define a policy: Route to dot_upstream first.
			if resolverMode == "forward_only" {
				content += `
-- Forward Only: Route all external queries to DoT pool (Dnsdist handles it)
addAction(AllRule(), PoolAction("dot_upstream"))
`
			} else if resolverMode == "hybrid" {
				content += `
-- Hybrid Mode: Prioritize DoT pool
-- Fallback automatically to auth_and_recursor pool if DoT is down (handled by multiple pools or explicit Lua)
addAction(AllRule(), PoolAction("dot_upstream"))
addAction(AllRule(), PoolAction("auth_and_recursor"))
`
			}
		} else {
			// No explicit DoT servers detected, send everything to recursor
			content += "\naddAction(AllRule(), PoolAction(\"auth_and_recursor\"))\n"
		}
	} else {
		// Root Only: Send everything to local recursor
		content += "\naddAction(AllRule(), PoolAction(\"auth_and_recursor\"))\n"
	}

	content += `
-- Performance tuning
setRingBuffersSize(10000000, 100)
setMaxUDPOutstanding(65535)

-- Web Console
webserver("0.0.0.0:8083", "admin", "admin")
`

	return os.WriteFile("/etc/powerdns/dnsdist.conf", []byte(content), 0644)
}
