-- Laman Labuh RPZ Config
-- Dynamically generated by NetShield Go API

-- Example of turning on RPZ with custom IP redirect
-- -- File RPZ Utama (17 Juta Domain Komdigi)
rpzFile("/etc/powerdns/rpz_compiled.zone", {defpol=Policy.Custom, defcontent="103.162.17.181"})

-- File RPZ Khusus dari Dashboard (Real-time C++ Zone loading)
rpzFile("/etc/powerdns/custom_whitelist.zone", {defpol=Policy.Passthru})
rpzFile("/etc/powerdns/custom_blacklist.zone", {defpol=Policy.Custom, defcontent="103.162.17.181"})
