-- Laman Labuh RPZ Config
-- Dynamically generated by NetShield Go API

-- Example of turning on RPZ with custom IP redirect
-- rpzFile("/etc/powerdns/trustpositif.rpz", {defpol=Policy.Custom, defcontent={"10.10.10.10"}})
