local-address=127.0.0.1
local-port=5355
daemon=no
threads=4
# Meringankan beban pdns-recursor karena hanya dilalui oleh query dirty
max-cache-entries=1000000
lua-config-file=/etc/powerdns/laman_labuh.lua
allow-from=127.0.0.0/8
# DNSSEC dimatikan di recursor karena Unbound yang akan validasi DNSSEC utama jika perlu
dnssec=off
