# NetShield DNS v2.0 PowerDNS Recursor Config
local-address=0.0.0.0
local-port=53
daemon=no
security-poll-suffix=

# API & Control
webserver=yes
webserver-address=127.0.0.1
webserver-port=8081
webserver-password=netshield-secret
api-key=netshield-secret

# Performance & Caching (Extreme Optimization)
max-cache-entries=5000000
max-packetcache-entries=5000000
threads=16
# Kernel load balancing stripped PowerDNS of CPU slices when 16 local dnsperf instances ran simultaneously.
# Restoring user-space Load Balancing logic as the optimal ceiling for Localhost Testing (30,000 QPS).
pdns-distributes-queries=yes
max-mthreads=4096
max-tcp-clients=2048
tcp-fast-open=256
serve-rfc1918=yes
edns-subnet-allow-list=

# Include Lua scripts for ACL and RPZ
lua-config-file=/etc/powerdns/laman_labuh.lua
lua-dns-script=/etc/powerdns/main.lua

# Security defaults: open up strictly to allow Lua to handle ACL
allow-from=0.0.0.0/0, ::/0

forward-zones-file=/etc/powerdns/forward_zones.txt
